package com.willpower.clap.mapper;

import com.github.pagehelper.Page;
import com.willpower.clap.entity.Persons;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PersonsMapper {

    Page<Persons> findAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated
     */
    int insert(Persons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated
     */
    int insertSelective(Persons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated
     */
    Persons selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Persons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Persons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Persons record);
}