package com.willpower.clap.mapper;

import com.willpower.clap.entity.SysRolePermission;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Component
@Mapper
public interface SysRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbggenerated
     */
    int insert(SysRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbggenerated
     */
    int insertSelective(SysRolePermission record);

    /**
     * 清除roleid的原有权限
     * @param roleId
     * @return
     */
    int deleteRolePermissionByRoleId(Integer roleId);

    /**
     * 批量插入角色权限
     * @param rpList
     */
    int insertByBatch(List<SysRolePermission> rpList);
}