package com.willpower.clap.mapper;

import com.willpower.clap.entity.SysUserRole;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Component
@Mapper
public interface SysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated
     */
    int insert(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated
     */
    int insertSelective(SysUserRole record);

    /**
     * 根据用户ID获取角色ID
     * @param uid
     * @return
     */
    List<SysUserRole> findRoleByUserId(Integer uid);

    /**
     * 用户授权批量插入
     * @param sysUserRoles
     * @return
     */
    int insertByBatch(List<SysUserRole> sysUserRoles);

    /**
     * 根据用户id删除用户授权
     * @param uid
     * @return
     */
    int deleteUserRoleByUid(Integer uid);
}